config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticate :user do
    resources :arguments
    resources :statements

    root to: 'arguments#index', as: :authenticated_root
  end

  root 'arguments#index'

end

app/models/argument.rb
class Argument < ActiveRecord::Base
  has_many :argument_views
  validates_presence_of :argument_views

  def self.new_with_statements(user, statements)
    argument = self.new
    view = argument.argument_views.new user: user
    statements_objects = statements.map {|content| Statement.find_or_initialize_by content: content }
    view.versions.new statements: statements_objects
    argument
  end
end

app/models/argument_view.rb
class ArgumentView < ActiveRecord::Base
  belongs_to :argument
  belongs_to :user
  has_many :versions, -> { order('created_at asc') }, class_name: 'ArgumentViewVersion'
  validates_presence_of :versions

  def last_version
    versions.last
  end
end

app/models/argument_view_version.rb
class ArgumentViewVersion < ActiveRecord::Base
  belongs_to :argument_view
  belongs_to :previous
  has_and_belongs_to_many :statements
  delegate :user, to: :argument_view
  validates_presence_of :statements
end

app/models/statement.rb
class Statement < ActiveRecord::Base
end

app/models/statement_vote.rb
class StatementVote < ActiveRecord::Base
  belongs_to :statement
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable

  validates_presence_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
end

app/controllers/arguments_controller.rb
class ArgumentsController < ApplicationController
  before_action :set_argument, only: [:show, :edit, :update, :destroy]

  # GET /arguments
  # GET /arguments.json
  def index
    @arguments = Argument.all
  end

  # GET /arguments/1
  # GET /arguments/1.json
  def show
  end

  # GET /arguments/new
  def new
    @argument = Argument.new
  end

  # GET /arguments/1/edit
  def edit
  end

  # POST /arguments
  # POST /arguments.json
  def create
    @argument = Argument.new_with_statements(current_user, JSON.parse(argument_params[:statements]))

    respond_to do |format|
      if @argument.save
        format.html { redirect_to @argument, notice: 'Argument was successfully created.' }
        format.json { render :show, status: :created, location: @argument }
      else
        format.html { render :new }
        format.json { render json: @argument.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /arguments/1
  # PATCH/PUT /arguments/1.json
  def update
    statements = JSON.parse(argument_params[:statements]).map {|content| Statement.find_or_initialize_by(content: content)}
    argument_view = @argument.argument_views.find_or_initialize_by(user:current_user)
    argument_view.versions.new(statements: statements)

    respond_to do |format|
      if argument_view.save
        format.html { redirect_to @argument, notice: 'Argument was successfully updated.' }
        format.json { render :show, status: :ok, location: @argument }
      else
        format.html { render :edit }
        format.json { render json: @argument.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /arguments/1
  # DELETE /arguments/1.json
  def destroy
    @argument.destroy
    respond_to do |format|
      format.html { redirect_to arguments_url, notice: 'Argument was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_argument
      @argument = Argument.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def argument_params
      params.fetch(:argument, {})
    end
end

app/controllers/statements_controller.rb
class StatementsController < ApplicationController
  before_action :set_statement, only: [:show, :edit, :update, :destroy]

  # GET /statements
  # GET /statements.json
  def index
    @statements = Statement.all
  end

  # GET /statements/1
  # GET /statements/1.json
  def show
  end

  # GET /statements/new
  def new
    @statement = Statement.new
  end

  # GET /statements/1/edit
  def edit
  end

  # POST /statements
  # POST /statements.json
  def create
    @statement = Statement.new(statement_params)

    respond_to do |format|
      if @statement.save
        format.html { redirect_to @statement, notice: 'Statement was successfully created.' }
        format.json { render :show, status: :created, location: @statement }
      else
        format.html { render :new }
        format.json { render json: @statement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statements/1
  # PATCH/PUT /statements/1.json
  def update
    respond_to do |format|
      if @statement.update(statement_params)
        format.html { redirect_to @statement, notice: 'Statement was successfully updated.' }
        format.json { render :show, status: :ok, location: @statement }
      else
        format.html { render :edit }
        format.json { render json: @statement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statements/1
  # DELETE /statements/1.json
  def destroy
    @statement.destroy
    respond_to do |format|
      format.html { redirect_to statements_url, notice: 'Statement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_statement
      @statement = Statement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def statement_params
      params.require(:statement).permit(:content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/arguments_helper.rb
module ArgumentsHelper
  def argument_versions argument
    argument.argument_views.map(&:last_version).map { |version|
      {
        view_id: version.argument_view_id,
        version_id: version.id,
        user: { id: version.user.id, name: version.user.name },
        lastmod: version.created_at,
        statements: version.statements.map(&:content)
      }
    }
  end
end

app/helpers/statements_helper.rb
module StatementsHelper
end

app/views/arguments/_form.html.haml
= form_for @argument do |f|
  = react_component 'Argument', versions: argument_versions(@argument)
  .actions
    = f.submit 'Save'
-#   - if @argument.errors.any?
-#     #error_explanation
-#       %h2= "#{pluralize(@argument.errors.count, "error")} prohibited this argument from being saved:"
-#       %ul
-#         - @argument.errors.full_messages.each do |msg|
-#           %li= msg
-#
-#

app/views/arguments/edit.html.haml
%h1 Editing argument

= render 'form'

= link_to 'Show', @argument
\|
= link_to 'Back', arguments_path

app/views/arguments/index.html.haml
%h1 Listing arguments

%table
  %thead
    %tr
      %th
      %th
      %th

  %tbody
    - @arguments.each do |argument|
      %tr
        %td= link_to 'Show', argument
        %td= link_to 'Edit', edit_argument_path(argument)
        %td= link_to 'Destroy', argument, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Argument', new_argument_path

app/views/arguments/new.html.haml
%h1 New argument

= render 'form'

= link_to 'Back', arguments_path

app/views/arguments/show.html.haml
%p#notice= notice
= form_for @argument do |f|
  = react_component 'Argument', versions: argument_versions(@argument)

= link_to 'Edit', edit_argument_path(@argument)
\|
= link_to 'Back', arguments_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Truebites</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/statements/_form.html.haml
= form_for @statement do |f|
  - if @statement.errors.any?
    #error_explanation
      %h2= "#{pluralize(@statement.errors.count, "error")} prohibited this statement from being saved:"
      %ul
        - @statement.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :content
    = f.text_area :content
  .actions
    = f.submit 'Save'

app/views/statements/edit.html.haml
%h1 Editing statement

= render 'form'

= link_to 'Show', @statement
\|
= link_to 'Back', statements_path

app/views/statements/index.html.haml
%h1 Listing statements

%table
  %thead
    %tr
      %th Content
      %th
      %th
      %th

  %tbody
    - @statements.each do |statement|
      %tr
        %td= statement.content
        %td= link_to 'Show', statement
        %td= link_to 'Edit', edit_statement_path(statement)
        %td= link_to 'Destroy', statement, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Statement', new_statement_path

app/views/statements/new.html.haml
%h1 New statement

= render 'form'

= link_to 'Back', statements_path

app/views/statements/show.html.haml
%p#notice= notice

%p
  %b Content:
  = @statement.content

= link_to 'Edit', edit_statement_path(@statement)
\|
= link_to 'Back', statements_path